server.port=8090

spring.datasource.url=jdbc:mysql://localhost:3306/expense_tracker?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=ashif@2005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwt.secret=MySecretKeyForExpenseTrackerApplicationThatIsLongEnoughToBeSecure
app.jwt.expiration=86400000

app.cors.allowed-origins=http://localhost:5173

logging.level.com.expensetracker=DEBUG